### ISSUE TITLE
Error de indexación.

### ISSUE THREAD

**Issue by frodriFulp** [Javier9684/PHP-practic-SKILLS_UP#2]
https://github.com/Javier9684/PHP-practic-SKILLS_UP/blob/64358e939d771773e13dd0cbbcb4462774a327f0/modules/include/news_reg.php#L73

En general, porque lo tienes en otras partes, los trozos de código que están dentro de un "if" deben de estar, al menos un nivel hacia la derecha" no al mismo de la apertura del "if". Revisar el código para que estén todo en los niveles que le corresponden.

**Se repasará en clase porque más personas tienen el mismo problema.**

**Comment by Javier9684** [comment]
Maqueao ;)
